### PR TITLE
Terms query

### PR DESCRIPTION
**Pull request by smock**
@prog8 this is meant to address https://github.com/sematext/solr-redis/issues/23 .  Is this along the right lines?  Many of the tests now fail as TermsQuery doesn't implement extractTerms.

### CODE REVIEW

**Comment by otisg** [comment]
@smock - look at https://github.com/sematext/solr-redis/search?utf8=%E2%9C%93&q=BooleanQuery
You'll see @prog8 implemented term extractor for BooleanQuery.  I assume you'd need to do the same for TermsQuery.

**Comment by prog8** [comment]
@smock yes you are right all test which verify terms in query will fail since ConstantScoreWeight doesn't allow to extract terms. I'll look at this closer.

**Comment by prog8** [comment]
The reason is that during TermsQuery rewrite there is the decission whether TermIterator should be used or just BooleanQuery. For small number of terms BooleanQuery is used and it is later wrapped in ConstantScoreQuery.

**Comment by smock** [comment]
In later versions of lucene-solr, we can use getTermData() on the query to get the number of terms for that check.  I'm updating my P.R. to work against Solr 6.0 -- it's what I'm using in my environment anyway.

**Comment by prog8** [comment]
I pushed fixed version. In Lucene 5.x getTermData is not exposed as public :-(

**Comment by smock** [comment]
Yes, I'll work on a separate p.r. for Lucene/Solr 6.0

**Pull request closed without merging**
