### PR TITLE
Solr 6

### PR DESCRIPTION
**Pull request by smock**
@prog8 This compiles against Solr 6, however I'm still not sure how to fix the tests.  I've also added a TermsQueryExtractor for use with TaggedQuery.

### CODE REVIEW

**Comment by prog8** [comment]
TermsQueryExtractor is not needed here. I fixed tests. You can fetch changes from master @smock

**Comment by smock** [comment]
@prog8 pulled in master and I'm no longer getting the original failed tests, however I believe because of my update of the Solr version I'm getting a new failure.  Any advice on how to fix?

**Comment by smock** [comment]
@prog8 I ran this against java8 and tests passed.

**Comment by prog8** [comment]
Hi I think Lucene/Solr 6 will work only on JDK 8

**Comment by smock** [comment]
That seems correct.  Any way to get this into the plugin in a branch?  Presumably the test runner would have to be updated.

**Comment by prog8** [comment]
Sure I'll do it ASAP. Unfortunately a little busy now :-(
I will create branch and tag with new version. I'll also modify Travis configuration

**Comment by smock** [comment]
Thanks!  No rush.

**Pull request merged**
